# Generated by Django 4.2 on 2023-04-12 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_sucursal_remove_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto_sucursal',
            options={'verbose_name': 'Producto_Sucursal', 'verbose_name_plural': 'Producto_Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='nombre',
            new_name='ciudad',
        ),
    ]
