# Generated by Django 4.2 on 2023-04-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_sucursal_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='categoria_id',
        ),
    ]
